version: "3.4"
services:
  builder:
    build:
      context: .
      target: builder
    volumes:
      - .:/app

  test:
    build:
      context: .
      target: test
    command: dotnet test

  web:
    build:
      context: .
      target: web
    ports:
      - 8080:80
    command: dotnet /app/consumer.dll

